### ISSUE TITLE
cuda execution failed with error 98 invalid device function

### ISSUE THREAD

**Issue by harveypham** [traveller59/spconv#140]
I ran second.pytorch on a docker container on AWS and got the following error:

```
File "/second/pytorch/models/voxelnet.py", line 364, in forward
preds_dict = self.network_forward(voxels, num_points, coors, batch_size_dev)
File "/second/pytorch/models/voxelnet.py", line 331, in network_forward
voxel_features, coors, batch_size)
File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
result = self.forward(*input, **kwargs)
File "/second/pytorch/models/middle.py", line 203, in forward
ret = self.middle_conv(ret)
File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
result = self.forward(*input, **kwargs)
File "/usr/local/lib/python3.6/dist-packages/spconv/modules.py", line 130, in forward
input = module(input)
File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
result = self.forward(*input, **kwargs)
File "/usr/local/lib/python3.6/dist-packages/spconv/conv.py", line 177, in forward
use_hash=self.use_hash)
File "/usr/local/lib/python3.6/dist-packages/spconv/ops.py", line 93, in get_indice_pairs
stride, padding, dilation, out_padding, int(subm), int(transpose), int(use_hash))
RuntimeError: /second.pytorch/spconv/src/spconv/indice.cu 165
cuda execution failed with error 98 invalid device function
prepareSubMHashKernel failed
```

nvidia-smi output:
```
Tue May 19 03:36:22 2020
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.87.00 Driver Version: 418.87.00 CUDA Version: 10.1 |
|-------------------------------+----------------------+----------------------+
| GPU Name Persistence-M| Bus-Id Disp.A | Volatile Uncorr. ECC |
| Fan Temp Perf Pwr:Usage/Cap| Memory-Usage | GPU-Util Compute M. |
|===============================+======================+======================|
| 0 Tesla V100-SXM2... On | 00000000:00:1B.0 Off | 0 |
| N/A 46C P0 41W / 300W | 0MiB / 16130MiB | 0% Default |
+-------------------------------+----------------------+----------------------+
| 1 Tesla V100-SXM2... On | 00000000:00:1C.0 Off | 0 |
| N/A 48C P0 38W / 300W | 0MiB / 16130MiB | 0% Default |
+-------------------------------+----------------------+----------------------+
| 2 Tesla V100-SXM2... On | 00000000:00:1D.0 Off | 0 |
| N/A 47C P0 41W / 300W | 0MiB / 16130MiB | 0% Default |
+-------------------------------+----------------------+----------------------+
| 3 Tesla V100-SXM2... On | 00000000:00:1E.0 Off | 0 |
| N/A 47C P0 42W / 300W | 0MiB / 16130MiB | 0% Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes: GPU Memory |
| GPU PID Type Process name Usage |
|=============================================================================|
| No running processes found |
+-----------------------------------------------------------------------------+
```
nvcc --version output:
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243
```

Other pytorch projects can use GPUs without any issue.

Docker image is based on nvidia/cuda:10.1-cudnn7-devel. 

Please help point me to the right direction to debug this issue.

**Comment by traveller59** [comment]
invalid device function is due to missing cuda arch flag during cuda compilation.
add '--verbose' to cmake build in setup.py and check gpu arch "sm_70" in cuda object build command.

**Comment by harveypham** [comment]
Thank you for really helpful hint. My issue was due to a slight difference between docker build machine and docker run machine.

**Comment by yuanzheng-s** [comment]
> invalid device function is due to missing cuda arch flag during cuda compilation.
> add '--verbose' to cmake build in setup.py and check gpu arch "sm_70" in cuda object build command.

@traveller59  how to check gpu arch ,my gpu is quadro p4000

**Comment by vaydingul** [comment]
> invalid device function is due to missing cuda arch flag during cuda compilation.
> add '--verbose' to cmake build in setup.py and check gpu arch "sm_70" in cuda object build command.

Hi @traveller59,

If it is not in the GPU architecture, how can we solve this? By changing the GPU or CUDA-cuDNN versions?

**Comment by juimoisnono** [comment]
I have met the same problem and I solved this by add cuda flags in setup.py like "cuda_flags += ["-gencode", "arch=compute_52,code=sm_52",
 "-gencode", "arch=compute_60,code=sm_60",
 "-gencode", "arch=compute_61,code=sm_61",
 "-gencode", "arch=compute_70,code=sm_70",
 "-gencode", "arch=compute_75,code=sm_75",
 "-gencode", "arch=compute_80,code=sm_80",
 "-gencode", "arch=compute_86,code=sm_86",
 "-gencode", "arch=compute_86,code=compute_86"];(remember you must know you own GPU Compute Capability)
and "set(CMAKE_VERBOSE_MAKEFILE ON)" in CMakeLists.txt

**Comment by jayadeepk** [comment]
@juimoisnono Your method works on my cuda 11.0 and compute 5.0. Thanks!
Since I am using an older spconv commit [8da6f96](https://github.com/traveller59/spconv/tree/8da6f96) for setting up [CLOCs](https://github.com/pangsu0613/CLOCs), I had to add those flags to -DCMAKE_CUDA_FLAGS in setup.py instead of cuda_flags.

**Comment by Markos2** [comment]
> I have met the same problem and I solved this by add cuda flags in setup.py like "cuda_flags += ["-gencode", "arch=compute_52,code=sm_52", "-gencode", "arch=compute_60,code=sm_60", "-gencode", "arch=compute_61,code=sm_61", "-gencode", "arch=compute_70,code=sm_70", "-gencode", "arch=compute_75,code=sm_75", "-gencode", "arch=compute_80,code=sm_80", "-gencode", "arch=compute_86,code=sm_86", "-gencode", "arch=compute_86,code=compute_86"];(remember you must know you own GPU Compute Capability) and "set(CMAKE_VERBOSE_MAKEFILE ON)" in CMakeLists.txt

I'm using **GT740M** and **470 Nvidia driver** with **compute at 3.0** max, I see in the latest dlib we can add those switches to the CMakeLists.txt and possibly not required in setup.py or would be redundant I think. Do I have to put just some compute values via the switches ranging from 10 to 30 or just one entry of ["-gencode", "arch=compute_30,code=sm_30"]?

My issue is not with dlib building as everything ends with DLIB can use CUDA & CUDNN but when it runs a prgram it gets
"_**RuntimeError: Error while calling cudaOccupancyMaxPotentialBlockSize(&num_blocks,&num_threads,K) in file /home/asusubuntu20/dlib/dlib/cuda/cuda_utils.h:186. code: 98, reason: invalid device function**_"
