### ISSUE TITLE
cuda execution failed with error 700 an illegal memory access was encountered

### ISSUE THREAD

**Issue by dhlrd** [traveller59/spconv#392]
Thanks for your work, now I counter the problem below when training during the backward 

Traceback (most recent call last):
  File "./src/main.py", line 105, in <module>
    main(opt)
  File "./src/main.py", line 73, in main
    log_dict_train, _ = trainer.train(epoch, train_loader)
  File "/dockerdata/hongliding/codes/pole-3d/src/lib/trains/base_trainer.py", line 136, in train
    return self.run_epoch('train', epoch, data_loader)
  File "/dockerdata/hongliding/codes/pole-3d/src/lib/trains/base_trainer.py", line 85, in run_epoch
    loss.backward()
  File "/dockerdata/hongliding/env/sp2py3.6/lib/python3.6/site-packages/torch/tensor.py", line 185, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/dockerdata/hongliding/env/sp2py3.6/lib/python3.6/site-packages/torch/autograd/__init__.py", line 127, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: /io/build/temp.linux-x86_64-3.6/spconv/build/src/cumm/conv/main/ConvMainUnitTest/ConvMainUnitTest_implicit_gemm2.cu 3187
cuda execution failed with error 700 an illegal memory access was encountered
???

my configuration is: cuda 10.2, spconv 2.1.12, Gpu v100, pytorch 1.6.0, python 3.6.8

**Comment by FindDefinition** [comment]
This kind of bug will be proceed with highest priority.
This kind of bug isn't easy to debug, I need you provide more information about this error:
1. change ```implicit_gemm_backward``` in spconv/pytorch/ops.py to:
```Python
def implicit_gemm_backward(features: torch.Tensor,
                           filters: torch.Tensor,
                           out_bp: torch.Tensor,
                           pair_fwd: torch.Tensor,
                           pair_bwd: torch.Tensor,
                           pair_mask_fwd_splits: List[torch.Tensor],
                           pair_mask_bwd_splits: List[torch.Tensor],
                           mask_argsort_fwd_splits: List[torch.Tensor],
                           mask_argsort_bwd_splits: List[torch.Tensor],
                           mask_output_fwd: torch.Tensor,
                           masks: List[np.ndarray],
                           mask_width: int,
                           is_subm: bool,
                           timer: CUDAKernelTimer = CUDAKernelTimer(False)):
    # print(out_bp.mean(), out_bp.max(), out_bp.min())
    torch.cuda.synchronize()
    import pickle 
    with open("/path/to/your/debug_data", "wb") as f:
        debug_data = (features.shape, filters.shape, out_bp.shape, pair_fwd, pair_bwd, 
            pair_mask_fwd_splits, pair_mask_bwd_splits, mask_argsort_fwd_splits,
            mask_argsort_bwd_splits, mask_output_fwd, masks, is_subm)
        pickle.dump(debug_data, f)
    if features.dtype == torch.int8 or features.dtype == torch.qint8:
        raise NotImplementedError("work in progress")
    if not out_bp.is_contiguous():
        out_bp = out_bp.contiguous()
    if not features.is_contiguous():
        features = features.contiguous()

    assert out_bp.is_contiguous()
    assert filters.is_contiguous()
    assert features.is_contiguous()
    # here filters is KRSC
    filters_shape = filters.shape
    out_channel = filters.shape[0]
    in_channel = filters.shape[-1]
    num_split = len(pair_mask_fwd_splits)
    if is_subm:
        din = torch.empty_like(features)
    else:
        din = torch.zeros_like(features)
    dfilters = torch.zeros_like(filters)

    filters = filters.reshape(out_channel, -1, filters.shape[-1])
    kv = filters.shape[1]

    stream = get_current_stream()
    pair_fwd_tv = torch_tensor_to_tv(pair_fwd)
    pair_bwd_tv = torch_tensor_to_tv(pair_bwd)

    features_tv = torch_tensor_to_tv(features)
    filters_tv = torch_tensor_to_tv(filters)
    dfilters_tv = torch_tensor_to_tv(dfilters)

    dout_tv = torch_tensor_to_tv(out_bp)
    din_tv = torch_tensor_to_tv(din)
    mask_output_fwd_tv = torch_tensor_to_tv(mask_output_fwd, dtype=tv.uint32)
    arch = torch.cuda.get_device_capability()
    pair_mask_fwd_split_tvs = [
        torch_tensor_to_tv(x, dtype=tv.uint32) for x in pair_mask_fwd_splits
    ]
    pair_mask_bwd_split_tvs = [
        torch_tensor_to_tv(x, dtype=tv.uint32) for x in pair_mask_bwd_splits
    ]

    mask_argsort_fwd_split_tvs = [
        torch_tensor_to_tv(x) for x in mask_argsort_fwd_splits
    ]
    mask_argsort_bwd_split_tvs = [
        torch_tensor_to_tv(x) for x in mask_argsort_bwd_splits
    ]

    dgrad_tune_res = CONV.get_tuned_algo(ConvOpType.kBackwardInput,
                                         din_tv.dtype, filters_tv.dtype,
                                         dout_tv.dtype, out_channel,
                                         in_channel, arch)
    wgrad_tune_res = CONV.get_tuned_algo(ConvOpType.kBackwardWeight,
                                         features_tv.dtype, dfilters_tv.dtype,
                                         dout_tv.dtype, out_channel,
                                         in_channel, arch, mask_width)

    if dgrad_tune_res is None:
        # TODO split mask maybe completely invalid
        if is_subm:
            mask = pair_mask_fwd_split_tvs[0]
            mask_argsort = mask_argsort_fwd_split_tvs[0]
        else:
            mask = pair_mask_bwd_split_tvs[0]
            mask_argsort = mask_argsort_bwd_split_tvs[0]

        dgrad_tune_res, _ = CONV.tune_and_cache(ConvOpType.kBackwardInput,
                                                din_tv,
                                                filters_tv,
                                                dout_tv,
                                                NHWC,
                                                KRSC,
                                                NHWC,
                                                arch,
                                                mask=mask,
                                                mask_argsort=mask_argsort,
                                                indices=pair_bwd_tv,
                                                reverse_mask=is_subm,
                                                mask_filter=masks[0].item(),
                                                stream=stream)
    if wgrad_tune_res is None:
        wgrad_tune_res, _ = CONV.tune_and_cache(
            ConvOpType.kBackwardWeight,
            features_tv,
            dfilters_tv,
            dout_tv,
            NHWC,
            KRSC,
            NHWC,
            arch,
            mask=pair_mask_fwd_split_tvs[0],
            mask_argsort=mask_argsort_fwd_split_tvs[0],
            indices=pair_fwd_tv,
            reverse_mask=False,
            mask_filter=masks[0].item(),
            mask_output=mask_output_fwd_tv[0],
            mask_width=mask_width,
            stream=stream)
    workspace_size = CONV.query_workspace_size(wgrad_tune_res.algo_desp,
                                               wgrad_tune_res.splitk,
                                               ConvOpType.kBackwardWeight,
                                               pair_fwd_tv.dim(1), in_channel,
                                               out_channel, kv)
    workspace = torch.Tensor()

    workspace_tv = tv.Tensor()
    if workspace_size > 0:
        workspace = torch.empty((workspace_size, ),
                                dtype=torch.int8,
                                device=features.device)
        workspace_tv = torch_tensor_to_tv(workspace)
    with timer.record("implicit_gemm_backward", stream):
        for j in range(num_split):
            beta = 0 if j == 0 else 1
            if is_subm:
                mask = pair_mask_fwd_split_tvs[j]
                mask_argsort = mask_argsort_fwd_split_tvs[j]
            else:
                mask = pair_mask_bwd_split_tvs[j]
                mask_argsort = mask_argsort_bwd_split_tvs[j]

            CONV.run_with_tuned_result(dgrad_tune_res,
                                       ConvOpType.kBackwardInput,
                                       din_tv,
                                       filters_tv,
                                       dout_tv,
                                       mask=mask,
                                       mask_argsort=mask_argsort,
                                       mask_output=tv.Tensor(),
                                       indices=pair_bwd_tv,
                                       reverse_mask=is_subm,
                                       mask_filter=masks[j].item(),
                                       mask_width=-1,
                                       beta=beta,
                                       stream=stream)
            CONV.run_with_tuned_result(
                wgrad_tune_res,
                ConvOpType.kBackwardWeight,
                features_tv,
                dfilters_tv,
                dout_tv,
                mask=mask_output_fwd_tv[j],
                mask_argsort=mask_argsort_fwd_split_tvs[j],
                mask_output=tv.Tensor(),
                indices=pair_fwd_tv,
                reverse_mask=False,
                mask_filter=masks[j].item(),
                mask_width=mask_width,
                beta=beta,
                workspace=workspace_tv,
                stream=stream)
    torch.cuda.synchronize()
    return (din, dfilters.reshape(filters_shape))

```
Change save path in code above to a correct path.
You can use ```python -c "import spconv;print(spconv.__file__)"``` to get location of installed code.
2. use ```CUDA_LAUNCH_BLOCKING=1 python ...``` to launch your code
3. upload saved file to somewhere I can download.

**Comment by FindDefinition** [comment]
You can use ```SPCONV_DEBUG_SAVE_PATH=$HOME/your_debug_file_name.pkl CUDA_LAUNCH_BLOCKING=1 python ...``` with spconv 2.1.13 to easily get debug log info and debug file for developer without modify any spconv code.

**Comment by dhlrd** [comment]
> You can use `SPCONV_DEBUG_SAVE_PATH=$HOME/your_debug_file_name.pkl CUDA_LAUNCH_BLOCKING=1 python ...` with spconv 2.1.13 to easily get debug log info and debug file for developer without modify any spconv code.

ok, I will try this, using the method modifyng the function of  implicit_gemm_backward didn't save any file, I don't know the reason.

**Comment by dhlrd** [comment]
> debug

/dockerdata/dhl/env/sp2/lib64/python3.6/site-packages/torch/nn/_reduction.py:44: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  warnings.warn(warning.format(ret))
[Exception|implicit_gemm_backward]feat=torch.Size([2828778, 16]),w=torch.Size([32, 3, 3, 3, 16]),pair=torch.Size([27, 2828778]),issubm=True,do=torch.Size([2828778, 32])
THCudaCheck FAIL file=/pytorch/torch/csrc/generic/serialization.cpp line=31 error=700 : an illegal memory access was encountered
spconv try to save debug data to data/debug.pkl, but failed with exception cuda runtime error (700) : an illegal memory access was encountered at /pytorch/torch/csrc/generic/serialization.cpp:31. please check your SPCONV_DEBUG_SAVE_PATH
Traceback (most recent call last):
  File "./src/main.py", line 105, in <module>
    main(opt)
  File "./src/main.py", line 73, in main
    log_dict_train, _ = trainer.train(epoch, train_loader)
  File "/dockerdata/dhl/codes/pole-3d/src/lib/trains/base_trainer.py", line 136, in train
    return self.run_epoch('train', epoch, data_loader)
  File "/dockerdata/dhl/codes/pole-3d/src/lib/trains/base_trainer.py", line 85, in run_epoch
    loss.backward()
  File "/dockerdata/dhl/env/sp2/lib64/python3.6/site-packages/torch/tensor.py", line 185, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/dockerdata/dhl/env/sp2/lib64/python3.6/site-packages/torch/autograd/__init__.py", line 127, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: /io/build/temp.linux-x86_64-3.6/spconv/build/src/cumm/conv/main/ConvMainUnitTest/ConvMainUnitTest_implicit_gemm2.cu 4779
cuda execution failed with error 700 an illegal memory access was encountered
???



hi, @FindDefinition the pkl file didn't save any information, the size of the save file is 0. and get this error info.

**Comment by FindDefinition** [comment]
I'm try to reproduce your bug in my environment.
Could you save indices which length is 2828778 and upload somewhere? you can modify spconv/pytorch/conv.py and save input.indices with if check (if input.indices.shape[0] == 2828778). I also need spatial shape of input tensor (input.spatial_shape).

**Comment by dhlrd** [comment]
the input spatial shape of my neural network is [4, 360, 96, 480, 1], 4 is batchsize, 1 is channel, 360*96*480 is the h*x*y,
and the input.spatial_shape in spconv/pytorch/conv.py forward function is [360, 96, 480].

the indice data is saved in the follow baidu net dist:
链接: https://pan.baidu.com/s/1fBzrcvToLM7iwcnipFHwuw  密码: on9s


my network concerns spconv3d is 

self.encoder3d = spconv.SparseSequential(
                spconv.SparseConv3d(1, 16, 3, stride=1, padding=1, indice_key="subm0"),
                nn.BatchNorm1d(16),
                nn.ReLU(),
                spconv.SubMConv3d(16, 32, 3, stride=1, padding=1, indice_key="subm1"),
                nn.BatchNorm1d(32),
                nn.ReLU(),
                spconv.SubMConv3d(32, 64, 3, stride=1, padding=1, indice_key="subm1"),
                nn.BatchNorm1d(64),
                nn.ReLU(),
                spconv.SubMConv3d(64, 2, 3, stride=1, padding=1, indice_key="subm1"),
                nn.BatchNorm1d(2),
                nn.ReLU(),)


the forward function of my neural network is 

    def forward(self, vox):

        pts = vox #  [4, 360, 96, 480, 1]
        sp_t = spconv.SparseConvTensor.from_dense(pts)
        vox_feat = self.encoder3d(sp_t)
        vox_feat = vox_feat.dense()
        

        b, c, d, h, w = vox_feat.shape # [4, 2, 360, 96, 480]
        image = vox_feat.view(b, c * d, h, w)

        inter = self.pre(image)



thanks

**Comment by dhlrd** [comment]
2828778 is the number of point clouds of the entire batch, my batch size is 4, each point cloud file is containing points less than 100w

**Comment by dhlrd** [comment]
maybe this bug is caused by batchsize>1, I am testing using batchsize=1, the training is correct and the loss can be printed, but now I have not finished testing the entire epoch.  But when using batchsize=4, the training procedure is crashed in the first 10 iterations(I print the log with 10 iterations) 
@FindDefinition

**Comment by FindDefinition** [comment]
Thanks for your detail information, I will solve this problem soon.

**Comment by FindDefinition** [comment]
Unfortunately I can't reproduce your problem with this script:
```Python
import numpy as np
import torch
from torch import nn
from spconv.core import ConvAlgo

import spconv.pytorch as spconv

class Net(nn.Module):
    def __init__(self):
        super().__init__()
        self.net = spconv.SparseSequential(
            spconv.SubMConv3d(16, 32, 3, bias=False, indice_key="c0"),
        )

    def forward(self, features, coors, enable_timer: bool = False):
        x = spconv.SparseConvTensor(features,
                                    coors,
                                    [360, 96, 480],
                                    4,
                                    enable_timer=enable_timer)
        return self.net(x)

def main():
    device = torch.device("cuda:0")
    dtype = torch.float32
    net = Net().cuda().to(dtype)

    indices = np.load("/home/yy/Downloads/indice.npy")
    N = indices.shape[0]
    indices_th = torch.from_numpy(indices).cuda()
    features_th = torch.rand(N, 16, dtype=dtype, device=device)
    out = net(features_th, indices_th)

    dout = np.random.uniform(-0.2, 0.2, out.features.shape).astype(np.float32)
    dout_t = torch.from_numpy(dout).to(device).to(dtype)

    out.features.backward(dout_t)

if __name__ == "__main__":
    main()
```
Could you share your origin dense tensor input in bug iteration? You can try to reproduce your bug in script above.

**Comment by dhlrd** [comment]
hi @FindDefinition, using your code is actually can't reproduce the bug, I modify the code using exactly the same architecture as my net can cause a similar error, which appeared sometimes when I used spconv2.

```python
import numpy as np
import torch
from torch import nn


import spconv.pytorch as spconv

class Net(nn.Module):
    def __init__(self):
        super().__init__()
        self.net = spconv.SparseSequential(
            spconv.SparseConv3d(1, 16, 3, stride=1, padding=1, indice_key="subm0"),
            nn.BatchNorm1d(16),
            nn.ReLU(),
            spconv.SubMConv3d(16, 32, 3, stride=1, padding=1, indice_key="subm1"),
            nn.BatchNorm1d(32),
            nn.ReLU(),
            spconv.SubMConv3d(32, 64, 3, stride=1, padding=1, indice_key="subm1"),
            nn.BatchNorm1d(64),
            nn.ReLU(),
            spconv.SubMConv3d(64, 2, 3, stride=1, padding=1, indice_key="subm1"),
            nn.BatchNorm1d(2),
            nn.ReLU(), 
        )

    def forward(self, feat, coors, enable_timer: bool = False):
        x = spconv.SparseConvTensor(feat,
                                    coors,
                                    [360, 96, 480],
                                    4,
                                    enable_timer=enable_timer)
        out = self.net(x)
        dense = out.dense()
        print(dense.shape, "dense shape")
        return dense

def main():
    device = torch.device("cuda:0")
    dtype = torch.float32
    net = Net().cuda().to(dtype)

    input_data = np.load("feat_0.npy")
    features_th = torch.from_numpy(input_data).to(device)
    indices = np.load("ind_0.npy")
    indices_th = torch.from_numpy(indices).to(device)
    out = net(features_th, indices_th)

    dout = np.random.uniform(-0.2, 0.2, out.shape).astype(np.float32)
    dout_t = torch.from_numpy(dout).to(device).to(dtype)

    out.backward(dout_t)

if __name__ == "__main__":
    main()

```

the feat data and the indice data is saved in the following net disk
链接: https://pan.baidu.com/s/1ZADCWsIleLj_T705NIuA3Q  密码: h3v2

the error is as follows

torch.Size([4, 2, 360, 96, 480]) dense shape
[Exception|implicit_gemm_backward]feat=torch.Size([2762634, 32]),w=torch.Size([64, 3, 3, 3, 32]),pair=torch.Size([27, 2762634]),issubm=True,do=torch.Size([2762634, 64])
SPCONV_DEBUG_SAVE_PATH not found, you can specify SPCONV_DEBUG_SAVE_PATH as debug data save path to save debug data which can be attached in a issue.
Traceback (most recent call last):
  File "sp.py", line 57, in <module>
    main()
  File "sp.py", line 54, in main
    out.backward(dout_t)
  File "/dockerdata/dhl/env/sp2/lib64/python3.6/site-packages/torch/tensor.py", line 185, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/dockerdata/dhl/env/sp2/lib64/python3.6/site-packages/torch/autograd/__init__.py", line 127, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: /io/build/temp.linux-x86_64-3.6/spconv/build/src/cumm/gemm/main/GemmMainUnitTest/GemmMainUnitTest_stream_synchronize.cc(11)
CUDA error 700


Thank you

**Comment by FindDefinition** [comment]
I  guess the bug is due to int32 overflow in conv kernel, that's why only you encounter this bug, will be fixed soon.

**Comment by FindDefinition** [comment]
Could you please upgrade your cuda to 11 and check whether bug still exists?
I can't reproduce your bug in my environment (CUDA 11.4), after recheck your bug, I find that CUDA 10.2 may have problem.

**Comment by FindDefinition** [comment]
you can use spconv 2.1.14 and check if that bug still exists.
I have made small changes to avoid possible cuda 10.2 problem, I'm not sure if that can solve your problem.

**Comment by dhlrd** [comment]
> you can use spconv 2.1.14 and check if that bug still exists. I have made small changes to avoid possible cuda 10.2 problem, I'm not sure if that can solve your problem.

File "/dockerdata/dhl/env/sp2/lib64/python3.6/site-packages/spconv/pytorch/__init__.py", line 7, in <module>
    from spconv.pytorch import functional, ops
  File "/dockerdata/dhl/env/sp2/lib64/python3.6/site-packages/spconv/pytorch/functional.py", line 29, in <module>
    from spconv.pytorch.hash import HashTable
  File "/dockerdata/dhl/env/sp2/lib64/python3.6/site-packages/spconv/pytorch/hash.py", line 20, in <module>
    from spconv.core_cc.csrc.hash.core import HashTable as _HashTable
ModuleNotFoundError: No module named 'spconv.core_cc.csrc.hash'; 'spconv.core_cc.csrc' is not a package

now it has this error

**Comment by dhlrd** [comment]
> Could you please upgrade your cuda to 11 and check whether bug still exists? I can't reproduce your bug in my environment (CUDA 11.4), after recheck your bug, I find that CUDA 10.2 may have problem.

upgrade cuda to 11.4 is difficult,  i have to upgrade my gpu driver, it is too trouble... if this bug finally cannot be solved, may be I will try this...

**Comment by FindDefinition** [comment]
@dhlrd 2.1.14 have a small bug, will be fixed in 2.1.15, you can remove ```from spconv.pytorch.hash import HashTable``` in ```/dockerdata/dhl/env/sp2/lib64/python3.6/site-packages/spconv/pytorch/functional.py``` for now and test this bug

**Comment by dhlrd** [comment]
> @dhlrd 2.1.14 have a small bug, will be fixed in 2.1.15, you can remove `from spconv.pytorch.hash import HashTable` in `/dockerdata/dhl/env/sp2/lib64/python3.6/site-packages/spconv/pytorch/functional.py` for now and test this bug

Now the training procedure seems correct, the error does not appear. After I finish training the entire epoch, I will tell you the final result. 

Thank you for your excellent work and reply.

**Comment by FindDefinition** [comment]
A description of this bug and change I made:
The maximum number of point cloud and channel size is limited by (N * C * itemsize) because we calculate stride offset in bytes [here](https://github.com/FindDefinition/cumm/blob/v0.2.3/cumm/conv/sparse_iters.py#L297), this problem will be completely solved if we change it to int64. However, int64 need more registers and may make our kernel runs slower. the best solution is generate kernel program in runtime (nvrtc). 
The maximum shape of issue author's data is [2880000, 64], it is huge but still not reach the limit if compiler optimize the (32 / 8) to 4. If compiler doesn't optimize it, the value will overflow and cause bug.
In my test, the CUDA 10.2 doesn't do that optimization, it generates strange PTX code and cause overflow problem.  However the CUDA 11.x optimize it correctly and generate right PTX code that won't cause overflow. We can see difference in [godbolt](https://godbolt.org/noscript/cuda). I optimize it manually in new version so the bug disappear for issue author's data.

**Comment by dhlrd** [comment]
problem solved, thank you

**Comment by Neleon** [comment]
When I running PVRCNN++ model (OpenPCDet), I ran into the same problem, the error message as below:

```python
[Exception|implicit_gemm_backward]feat=torch.Size([803624, 16]),w=torch.Size([32, 3, 3, 3, 16]),pair=torch.Size([27, 783567]),issubm=False,do=torch.Size([783567, 32])
SPCONV_DEBUG_SAVE_PATH not found, you can specify SPCONV_DEBUG_SAVE_PATH as debug data save path to save debug data which can be attached in a issue.
Traceback (most recent call last):                                                                                 
  File "train.py", line 203, in <module>
    main()
  File "train.py", line 155, in main
    train_model(
  File "/root/algorithms/tools/train_utils/train_utils.py", line 106, in train_model
    accumulated_iter = train_one_epoch(
  File "/root/algorithms/tools/train_utils/train_utils.py", line 53, in train_one_epoch
    loss.backward()
  File "/usr/local/lib/python3.8/site-packages/torch/_tensor.py", line 255, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/usr/local/lib/python3.8/site-packages/torch/autograd/__init__.py", line 147, in backward
    Variable._execution_engine.run_backward(
  File "/usr/local/lib/python3.8/site-packages/torch/autograd/function.py", line 87, in apply
    return self._forward_cls.backward(self, *args)  # type: ignore[attr-defined]
  File "/usr/local/lib/python3.8/site-packages/torch/autograd/function.py", line 204, in wrapper
    outputs = fn(ctx, *args)
  File "/usr/local/lib/python3.8/site-packages/torch/cuda/amp/autocast_mode.py", line 236, in decorate_bwd
    return bwd(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/spconv/pytorch/functional.py", line 258, in backward
    raise e 
  File "/usr/local/lib/python3.8/site-packages/spconv/pytorch/functional.py", line 234, in backward
    input_bp, filters_bp = ops.implicit_gemm_backward(
  File "/usr/local/lib/python3.8/site-packages/spconv/pytorch/ops.py", line 1256, in implicit_gemm_backward
    dgrad_tune_res, _ = CONV.tune_and_cache(ConvOpType.kBackwardInput,
  File "/usr/local/lib/python3.8/site-packages/spconv/algo.py", line 661, in tune_and_cache
    GemmMainUnitTest.stream_synchronize(stream)
RuntimeError: /io/build/temp.linux-x86_64-3.8/spconv/build/src/cumm/gemm/main/GemmMainUnitTest/GemmMainUnitTest_stream_synchronize.cc(11)
CUDA error 700
```
When I removed `from spconv.pytorch.hash import HashTable` in `/usr/local/lib/python3.8/site-packages/spconv/pytorch/functional.py`, the error still exist.
When I set samples_per_gpu to 8 from 10, the error disappeared. 
My GPU is NVIDIA-A100-80GB, samples_per_gpu=8 consumes about 36GB, the samples_per_gpu can be set to 16 theoretically, no other applications running on the same node.
Additionly, spconv v1.x runs OK.

Can you give me some advice please? Thanks!
