### ISSUE TITLE
batch size problem

### ISSUE THREAD

**Issue by erinchen824** [traveller59/spconv#483]
Hi, thanks for your great work!
I am trying to use the 'spconv.SubMConv3d' function to explore some tasks, however, when the batch size is 1, the model can go through the entire dataset, while batch size is 2, it can go through one third of the dataset while batch size is 4, then it break down with the following error

`File "/media/cyj/DATA/Skeleton-AR/pointcloud/DepthPC/models/spmconv_pst.py", line 184, in forward
    x = self.conv1(input_sp_tensor)
  File "/home/cyj/anaconda3/envs/openpcdet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/cyj/anaconda3/envs/openpcdet/lib/python3.8/site-packages/spconv/pytorch/modules.py", line 137, in forward
    input = module(input)
  File "/home/cyj/anaconda3/envs/openpcdet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/cyj/anaconda3/envs/openpcdet/lib/python3.8/site-packages/spconv/pytorch/modules.py", line 137, in forward
    input = module(input)
  File "/home/cyj/anaconda3/envs/openpcdet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/cyj/anaconda3/envs/openpcdet/lib/python3.8/site-packages/spconv/pytorch/pool.py", line 167, in forward
    res = ops.get_indice_pairs_implicit_gemm(
  File "/home/cyj/anaconda3/envs/openpcdet/lib/python3.8/site-packages/spconv/pytorch/ops.py", line 293, in get_indice_pairs_implicit_gemm
    pair = torch.full((kv, indices.shape[0]),
RuntimeError: CUDA error: invalid configuration argument`

I have checked line 293 in 'get_indice_pairs_implicit_gemm',  it seems used for regular conv while I only use the submanifold sparse conv in the model.

Could you please help me with this? thx

**Comment by erinchen824** [comment]
> Hi, thanks for your great work! I am trying to use the 'spconv.SubMConv3d' function to explore some tasks, however, when the batch size is 1, the model can go through the entire dataset, while batch size is 2, it can go through one third of the dataset while batch size is 4, then it break down with the following error
> 
> `File "/media/cyj/DATA/Skeleton-AR/pointcloud/DepthPC/models/spmconv_pst.py", line 184, in forward x = self.conv1(input_sp_tensor) File "/home/cyj/anaconda3/envs/openpcdet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl return forward_call(*input, **kwargs) File "/home/cyj/anaconda3/envs/openpcdet/lib/python3.8/site-packages/spconv/pytorch/modules.py", line 137, in forward input = module(input) File "/home/cyj/anaconda3/envs/openpcdet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl return forward_call(*input, **kwargs) File "/home/cyj/anaconda3/envs/openpcdet/lib/python3.8/site-packages/spconv/pytorch/modules.py", line 137, in forward input = module(input) File "/home/cyj/anaconda3/envs/openpcdet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl return forward_call(*input, **kwargs) File "/home/cyj/anaconda3/envs/openpcdet/lib/python3.8/site-packages/spconv/pytorch/pool.py", line 167, in forward res = ops.get_indice_pairs_implicit_gemm( File "/home/cyj/anaconda3/envs/openpcdet/lib/python3.8/site-packages/spconv/pytorch/ops.py", line 293, in get_indice_pairs_implicit_gemm pair = torch.full((kv, indices.shape[0]), RuntimeError: CUDA error: invalid configuration argument`
> 
> I have checked line 293 in 'get_indice_pairs_implicit_gemm', it seems used for regular conv while I only use the submanifold sparse conv in the model.
> 
> Could you please help me with this? thx

Problem solved.
The error occurs because the input tensor is too large, it can be solved by a pooling on the input data.
THX!
