### ISSUE TITLE
TensorRT: encountered cuda error 700 during inference

### ISSUE THREAD

**Issue by HoiM** [traveller59/spconv#617]
Has anyone encountered this porblem when using TensorRT to do inference?

[07/04/2023-10:04:52] [I] Starting inference
[07/04/2023-10:04:53] [E] [TRT] /home/vision/Desktop/sparseconv_trt_new_libspconv/third_party/libspconv/spconv/src/spconvlib/cumm/conv/main/ConvMainUnitTest/ConvMainUnitTest_matmul_split_Ampere_f32f32f32_0.cu:399
cuda execution failed with error 700 an illegal memory access was encountered
Ampere_f32f32f32f32f32tnt_m32n32k16m16n16k16A0T1688_200_C301LLL_SK error with params [13905, 32] [32, 9, 32] [13905, 32] [9, 13905] [13905] [13905] [] -1
[07/04/2023-10:04:53] [E] Error[1]: [cudaDriverHelpers.cpp::cudaEventRecordWithExternalEvent::134] Error Code 1: Cuda Driver (an illegal memory access was encountered)
Cuda failure: an illegal memory access was encountered
Aborted (core dumped)
run_trtexec.sh: 19:
trtexec --loadEngine=spconv_deploy/onnx2trt/model.trt --loadInputs=voxels:spconv_deploy/onnx2trt/trt_input_output/voxels.bin,coords:spconv_deploy/onnx2trt/trt_input_output/coords.bin,voxel_num:spconv_deploy/onnx2trt/trt_input_output/voxel_num_10k.bin --exportOutput=spconv_deploy/onnx2trt/trt_input_output/output.json --verbose : not found

I created the TensorRT plugin by referring to the main.cu file. But when the number of points is dense enough, this error appears. When I ran the trtexec on 3080, this error appears as the number of points exceeds 50k. The same error occurs on Orin as the number of points exceeds 10k. The number of channels is always 32, which apparentlly does not exceed the range of int32. 

I also experimented with pytorch. But I found via nsight systems that pytorch and tensorrt use different kernels (simt vs ampere).

Appreciate your help!

**Comment by superpigforever** [comment]
Hi, May I ask what is the latency of your plugin?

**Comment by HoiM** [comment]
> Hi, May I ask what is the latency of your plugin?

On Jetson Orin, given 10k points, a three-layer sparse-conv network (32 channels) runs at a speed of 6.2ms

**Comment by superpigforever** [comment]
> > Hi, May I ask what is the latency of your plugin?
> 
> On Jetson Orin, given 10k points, a three-layer sparse-conv network (32 channels) runs at a speed of 6.2ms

By three-layer, do you mean three blocks or three conv? And is this running on fp16 or fp32?

**Comment by HoiM** [comment]
> > > Hi, May I ask what is the latency of your plugin?
> > 
> > 
> > On Jetson Orin, given 10k points, a three-layer sparse-conv network (32 channels) runs at a speed of 6.2ms
> 
> By three-layer, do you mean three blocks or three conv? And is this running on fp16 or fp32?

three blocks, the block does not have relu since sparse-conv itself has activation layer. And I use fp32

**Comment by HoiM** [comment]
My problem has been solved. Just a bug created by my teammate. Now I close the issue.

**Comment by hawl666** [comment]
@HoiM hi,What are the cuda and jetpack versions you used to run spconv inference on orin?
