### ISSUE TITLE
cudahash: Completely failed to build

### ISSUE THREAD

**Issue by He-Yunqian** [traveller59/spconv#66]
Hi, what caused this issue blew:

cudahash: Completely failed to build
Cuda error in file '/spconv/src/cuhash/hash_table.cpp' in line 194 : an illegal memory access was encountered.

**Comment by turboxin** [comment]
same error

**Comment by qchenclaire** [comment]
Typically this error happens when cuda out of memory or when you use multi gpus, you try to do some binary operations on tensors on different gpus. In my case, this error happens only when using multi gpus and only processes(I use distributed training) not on gpu 0 fail. I guess there are some code in this repo that loads some tensor to gpu 0 and then causes error on other processes.

**Comment by cvnerds** [comment]
This problem also occurs with single GPU during training and evaluation.

**Comment by HenryJunW** [comment]
Same problem with multiple GPUs, any solutions yet? Thanks

**Comment by PepperAndSalt** [comment]
Same problem with single GPU here. My is 2070

**Comment by TangeniThePyGuru** [comment]
Same problem here, running on single GPU.

**Comment by oreo-lp** [comment]
Same problem here, running on single GPU. My ia 2070 too!

**Comment by oreo-lp** [comment]
when i set my batch size to 1, it has no problem; However, when i set 2, it met this problem
i am very confused.

**Comment by oreo-lp** [comment]
maybe it out of memroy

**Comment by pyun-ram** [comment]
Same problem here, running on a single GPU. Mine is 1080Ti.
If I fix the random seed, the "Completely failed to build" problem can be reproduced at the specific data point.

**Comment by pyun-ram** [comment]
From the src/spconv/hash_table.cpp, the problem raised due to num_attempts >= kMaxRestartAttempts.
For cuckoo hashing, it has chances of meeting hash conflicts when the table size is small.
Therefore, I change the space usage factor when initializing the hash table by 
```cpp
//table.Initialize(numActIn, 2.0, 4);
table.Initialize(numActIn, 4.0, 4);
```
in src/spconv/indice.cu.
After modifying the code, I recompile and reinstall the spconv, then it works for me now.
Hope it helps in solving your cases. :)
