### ISSUE TITLE
Point Cloud Sparse Tensor error with SubMConv3dLayer: SubMmerge_sort: failed on 2nd step: cudaErrorIllegalAddress: an illegal memory access was encountered

### ISSUE THREAD

**Issue by JamesMcCullochDickens** [traveller59/spconv#712]
I'm trying to write code to go from a point cloud to a sparse tensor, and then do a SubMConv3dLayer convolution on the resulting sparse tensor. Here is what I have:

```
from typing import Union, Tuple, Optional

import torch, torch.nn as nn
import spconv.pytorch as spconv


def pcs_to_sparse_tensor(pcs: torch.Tensor, grid_size: float, pc_range: Tuple[float, float, float, float, float, float],
                         device_id: Optional[int], pad: int = 0) -> spconv.SparseConvTensor:
    batch_size, num_points, C = pcs.shape
    for i in range(3):
        pcs[:, :, i] = torch.clamp(pcs[:, :, i], min=pc_range[i], max=pc_range[i+3])
    pc_xyz_min = torch.tensor([pc_range[0], pc_range[1], pc_range[2]]).view(1, 1, 3)
    displaced_coords = pcs-pc_xyz_min
    coords = torch.div(displaced_coords, grid_size, rounding_mode="trunc").int()
    coords = coords.reshape(-1, 3)
    feats = pcs.reshape(-1, 3)
    spatial_shape = []
    for i in range(3):
        spatial_shape.append(int(((pc_range[3]-pc_range[0])/grid_size) + pad))
    repeat_vals = torch.tensor([num_points for _ in range(batch_size)])
    batch_vals = torch.arange(0, batch_size, step=1)
    batch_idx = torch.repeat_interleave(batch_vals, repeat_vals)
    indices = torch.cat([batch_idx.unsqueeze(-1).int(), coords], dim=1).contiguous()
    if device_id is not None:
        feats = feats.to(device_id)
        indices = indices.to(device_id)
    sp_tensor = spconv.SparseConvTensor(
        features=feats,
        indices=indices,
        spatial_shape=spatial_shape,
        batch_size=batch_size
    )
    return sp_tensor



rand_pcs = torch.rand(3, 500, 3)
sp = pcs_to_sparse_tensor(rand_pcs, grid_size=0.01, device_id=2, pc_range=(-1., -1., -1., 1., 1., 1.))
layer = spconv.SubMConv3d(in_channels=3, out_channels=6,
                                      kernel_size=3, indice_key="l1", padding=1,
                                      stride=1, dilation=0).to(2)
output = layer(sp)
```

I'm getting the error:

"[Exception|implicit_gemm_pair]indices=torch.Size([1500, 4]),bs=3,ss=[300, 300, 300],algo=ConvAlgo.MaskImplicitGemm,ksize=[3, 3, 3],stride=[1, 1, 1],padding=[1, 1, 1],dilation=[0, 0, 0],subm=True,transpose=False
Traceback (most recent call last):
  File "/home/jamesdickens/miniconda3/envs/pointcept/lib/python3.8/site-packages/spconv/pytorch/conv.py", line 408, in _conv_forward
    raise e
  File "/home/jamesdickens/miniconda3/envs/pointcept/lib/python3.8/site-packages/spconv/pytorch/conv.py", line 385, in _conv_forward
    res = ops.get_indice_pairs_implicit_gemm(
  File "/home/jamesdickens/miniconda3/envs/pointcept/lib/python3.8/site-packages/spconv/pytorch/ops.py", line 550, in get_indice_pairs_implicit_gemm
    SpconvOps.sort_1d_by_key_allocator(pair_mask_tv[j],
RuntimeError: merge_sort: failed on 2nd step: cudaErrorIllegalAddress: an illegal memory access was encountered"

Any thoughts what I might be doing wrong? I'd be happy to give any other relevant details.

**Edit: The error only occurs for gpu 2 and not gpu 0.**

**Comment by JamesMcCullochDickens** [comment]
I seem to have fixed this issue looking at another github issue here:
https://github.com/traveller59/spconv/issues/387

`torch.cuda.set_device(device_id) `

does the trick.

I haven't tried with distributed training yet but all seems good now. I guess there is some hardcoding of gpu 0 in the ops file somehow? Not sure. Anyway thanks for the great repo.

**Comment by zjw102** [comment]
Hello, I'm also experiencing this problem, I looked at your workaround, but I don't know how to solve it so specifically, can you guide me, my error is as follows：Original Traceback (most recent call last):
  File "/home/zjw/anaconda3/envs/last/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/home/zjw/anaconda3/envs/last/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/z_home/zjw/projects/Bridge3D-main/Pretrain/models/ReCon.py", line 359, in forward
    data_dict = cur_module(data_dict)
  File "/home/zjw/anaconda3/envs/last/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/z_home/zjw/projects/Bridge3D-main/Pretrain/models/vision_backbones_3d/spconv_unet_indoor.py", line 64, in forward
    output = self.input_conv(input_sp_tensor)
  File "/home/zjw/anaconda3/envs/last/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zjw/anaconda3/envs/last/lib/python3.8/site-packages/spconv/pytorch/modules.py", line 138, in forward
    input = module(input)
  File "/home/zjw/anaconda3/envs/last/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zjw/anaconda3/envs/last/lib/python3.8/site-packages/spconv/pytorch/conv.py", line 755, in forward
    return self._conv_forward(self.training,
  File "/home/zjw/anaconda3/envs/last/lib/python3.8/site-packages/spconv/pytorch/conv.py", line 408, in _conv_forward
    raise e
  File "/home/zjw/anaconda3/envs/last/lib/python3.8/site-packages/spconv/pytorch/conv.py", line 385, in _conv_forward
    res = ops.get_indice_pairs_implicit_gemm(
  File "/home/zjw/anaconda3/envs/last/lib/python3.8/site-packages/spconv/pytorch/ops.py", line 550, in get_indice_pairs_implicit_gemm
    SpconvOps.sort_1d_by_key_allocator(pair_mask_tv[j],
RuntimeError: merge_sort: failed on 2nd step: cudaErrorIllegalAddress: an illegal memory access was encountered
The specific code is as follows：
import torch
import functools
import torch.nn as nn

from utils.spconv_utils import spconv
from models.model_utils.unet_blocks import ResidualBlock, VGGBlock, UBlock
from utils import common_utils


class SparseUNetIndoor(nn.Module):
    def __init__(self, model_cfg):
        super(SparseUNetIndoor, self).__init__()
        norm_fn = functools.partial(nn.BatchNorm1d, eps=1e-4, momentum=0.1)

        self.model_cfg = model_cfg
        self.in_channel = model_cfg.IN_CHANNEL
        self.mid_channel = model_cfg.MID_CHANNEL
        self.block_reps = model_cfg.BLOCK_REPS
        self.block_residual = model_cfg.BLOCK_RESIDUAL
        self.num_blocks = model_cfg.get('NUM_BLOCKS', None)
        self.num_filters = model_cfg.get('NUM_FILTERS', None)

        if self.block_residual:
            block = functools.partial(ResidualBlock, custom_sp1x1=self.model_cfg.get('CUSTOM_SP1X1', False))
        else:
            block = VGGBlock
        device = torch.cuda.set_device('cuda:0')
        self.input_conv = spconv.SparseSequential(
            spconv.SubMConv3d(
                self.in_channel, self.mid_channel, kernel_size=3, padding=1, bias=False, indice_key='subm1'
            )
        )
        self.input_conv.to(device)

        if self.num_filters is not None:
            block_channels = self.num_filters
        else:
            assert self.num_blocks is not None
            block_channels = [self.mid_channel * (i + 1) for i in range(self.num_blocks)]

        self.unet = UBlock(block_channels, norm_fn, self.block_reps, block, indice_key_id=1)
        self.output_layer = spconv.SparseSequential(
            norm_fn(self.mid_channel), nn.ReLU()
        )

        # init parameters
        self.apply(self.set_bn_init)

    @staticmethod
    def set_bn_init(m):
        classname = m.__class__.__name__
        if classname.find('BatchNorm') != -1:
            m.weight.data.fill_(1.0)
            m.bias.data.fill_(0.0)

    def forward(self, batch_dict):

        input_sp_tensor = spconv.SparseConvTensor(
            batch_dict['voxel_features'], batch_dict['voxel_coords'].int(),
            batch_dict['spatial_shape'], batch_dict['batch_size']
        )
        output = self.input_conv(input_sp_tensor)
        output = self.unet(output)
        output = self.output_layer(output)
        output_feats = output.features
        # if not self.training and batch_dict['test_x4_split']:
        #     output_feats = common_utils.merge_4_parts(output_feats)

        batch_dict['backbone_3d_feats'] = output_feats
        return batch_dict
Where should I use torch.cuda.set_device (device_id), can you be specific, I look forward to your reply！

**Comment by JamesMcCullochDickens** [comment]
If you are doing multi-gpu training (this was the original context of my error and the fix), then you should set it at the beginning of each gpu's process, i.e. after the launch, and before the model is declared and put on the gpu. My fix essentially says treat GPU X as GPU 0, that way the hard-coded gpu loading of the spconv library doesn't fail since it assumes the data/model will be on gpu 0. Hope this helps.
