### ISSUE TITLE
Illegal memory access in cuhash

### ISSUE THREAD

**Issue by nslay** [traveller59/spconv#74]
Referencing this issue:
https://github.com/traveller59/second.pytorch/issues/229

Same crash at line 194 of cuhash/hash_table.cpp, only I'm not training. I'm evaluating a model!

It reliably happens on my data when numAct = 1024 (in spconv/index.cu) which is the max_table_size in cuhash's Build(). My suspicion is that the table_size calculation in cuhash is slightly incorrect.

That calculation is done here:
https://github.com/traveller59/spconv/blob/master/src/cuhash/hash_table.cpp#L102

If I change it to:
`    table_size_ = unsigned(floor(max_table_entries * space_usage) + 1); `

This is _definitely_ enough space since: floor(x) + 1 >= ceil(x) with floor(x) + 1 > ceil(x) when x is an integer.

That seems to prevent the "Illegal memory access" error from occurring. It's cringe-worthy to think that the corruption could be on the GPU side? Like it was writing one extra entry after the end of d_contents_? That array is stored on the GPU!

I need to study cuhash more to see why the current table_size might lead to corruption. Otherwise, I've run the thing 3 times on 5 minutes worth of data and it never crashes now. However, it always crashed before, without fail! And always when max_table_size is 1024.

**Comment by pyun-ram** [comment]
Thanks for your sharing! Your modification solved my problem. :)

**Comment by nslay** [comment]
> Thanks for your sharing! Your modification solved my problem. :)

Yeah, I'm not convinced that this will always solve the problem. I don't get illegal memory accesses anymore myself, however I have noticed someone else who initially wrote it solved their problem in the linked issue for training second.pytorch and soon after they deleted their post.

I am currently working on definitively identifying the problem and if I succeed and don't give up, I will post my solution here (or confirmation that this is indeed the fix).

**Comment by nslay** [comment]
I've reverted my change and rebuilt spconv with -fsanitizer=address on an Xavier and I've been hammering it with real data for about 30 minutes now. I cannot reproduce this problem. I could only get this to happen on x86_64 (that machine was borrowed and taken away from me)!

If you'd like to jump in and try -fsanitizer=address on x86_64, here's what you would do (normally):
1) Delete the 'build' folder in the spconv folder (if any) and make a backup of the 'dist' folder (if any). Oh yeah, revert the change I proposed if you made it!
2) export CXXFLAGS="-fsanitizer=address"; export LDFLAGS="-fsanitizer=address"
3) python3 setup.py bdist_wheel
4) cd dist; pip3 install --upgrade --force-reinstall spconv-1.1-cp36-cp36m-linux_aarch64.whl
5) export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libasan.so.4
6) export ASAN_OPTIONS="detect_leaks=0"
7) Train/test/run second.pytorch as you normally would. (Chances are, this won't work on Ubuntu!).

If it doesn't work, here's the abnormal way to try to do this! Only do this if you see this kind of message:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=84428

8) Build your own AddressSanitizer by following these instructions (make sure your LDFLAGS/CXXFLAGS as above are unset!):
https://github.com/google/sanitizers/wiki/AddressSanitizerHowToBuild
Instead of building all of LLVM, you can just: make -j12 asan
9) Go to: /usr/lib/x86_64-linux-gnu/ and: sudo mv libasan.so.4 libasan.so.4.bak  (**Put it back the way it was when you finish**)
10) In the llvm build folder: cd lib/clang/<llvm_version>/lib/linux/ and then ln -s libclang_rt.asan-x86_64.so libasan.so.4
11) export LD_LIBRARY_PATH="/path/to/LLVM/lib/clang/<llvm_version>/lib/linux:${LD_LIBRARY_PATH}"
12) export LD_PRELOAD=/path/to/LLVM/lib/clang/<llvm_version>/lib/linux/libasan.so.4
13) And _now_ train/test second.pytorch.

Hopefully you will find an AddressSanitizer log message with the location of the corruption (hopefully somewhere within spconv, otherwise we won't find it!).

I will try to get ahold of another x86_64 machine!

P.S. I am suspicious of simply slotting an LLVM AddressSanitizer library into a GCC-compiled application. I can't guarantee it will work!

**Comment by cvnerds** [comment]
Many thanks for sharing a workaround! For me too training as well as evaluating was problematic in some rare circumstances. I increased number of training steps 10-fold which would increase the odds of the problem happening. Sometimes simply resuming training via --resume would work, sometimes not.

I suppose if space_usage is a varying entity dependant on the current state of the GPU then that would explain why it appears non-deterministic (just a random thought).

**Comment by pyaf** [comment]
@nslay here are my outputs:
running point no. 5 and 6:
![pic-selected-191001-0333-35](https://user-images.githubusercontent.com/17473589/65920416-94400c80-e3fc-11e9-9d7a-8c12fadde1b0.png)

rerunning the program
![pic-selected-191001-0335-20](https://user-images.githubusercontent.com/17473589/65920441-a0c46500-e3fc-11e9-8636-fb05d7f2b605.png)

**Comment by andyt9527** [comment]
> I've reverted my change and rebuilt spconv with -fsanitize=address on an Xavier and I've been hammering it with real data for about 30 minutes now. I cannot reproduce this problem. I could only get this to happen on x86_64 (that machine was borrowed and taken away from me)!
> 
> If you'd like to jump in and try -fsanitize=address on x86_64, here's what you would do (normally):
> 
> 1. Delete the 'build' folder in the spconv folder (if any) and make a backup of the 'dist' folder (if any). Oh yeah, revert the change I proposed if you made it!
> 2. export CXXFLAGS="-fsanitize=address"; export LDFLAGS="-fsanitize=address"
> 3. python3 setup.py bdist_wheel
> 4. cd dist; pip3 install --upgrade --force-reinstall spconv-1.1-cp36-cp36m-linux_aarch64.whl
> 5. export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libasan.so.4
> 6. export ASAN_OPTIONS="detect_leaks=0"
> 7. Train/test/run second.pytorch as you normally would. (Chances are, this won't work on Ubuntu!).
> 
> If it doesn't work, here's the abnormal way to try to do this! Only do this if you see this kind of message: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=84428
> 
> 8. Build your own AddressSanitizer by following these instructions (make sure your LDFLAGS/CXXFLAGS as above are unset!):
>    https://github.com/google/sanitizers/wiki/AddressSanitizerHowToBuild
>    Instead of building all of LLVM, you can just: make -j12 asan
> 9. Go to: /usr/lib/x86_64-linux-gnu/ and: sudo mv libasan.so.4 libasan.so.4.bak  (**Put it back the way it was when you finish**)
> 10. In the llvm build folder: cd lib/clang/<llvm_version>/lib/linux/ and then ln -s libclang_rt.asan-x86_64.so libasan.so.4
> 11. export LD_LIBRARY_PATH="/path/to/LLVM/lib/clang/<llvm_version>/lib/linux:${LD_LIBRARY_PATH}"
> 12. export LD_PRELOAD=/path/to/LLVM/lib/clang/<llvm_version>/lib/linux/libasan.so.4
> 13. And _now_ train/test second.pytorch.
> 
> Hopefully you will find an AddressSanitizer log message with the location of the corruption (hopefully somewhere within spconv, otherwise we won't find it!).
> 
> I will try to get ahold of another x86_64 machine!
> 
> P.S. I am suspicious of simply slotting an LLVM AddressSanitizer library into a GCC-compiled application. I can't guarantee it will work!
> 
> EDIT: It's -fsanitize not -fsanitizer!

how to build spconv whl for aarch64 , please?
